// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace WebSQL.Controllers
{
    public partial class HomeController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public HomeController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected HomeController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult FetchColumns()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.FetchColumns);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult LoginToServer()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.LoginToServer);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult RunSQL2()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.RunSQL2);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public HomeController Actions { get { return MVC.Home; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Home";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Home";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string Start = "Start";
            public readonly string LoginToServerAuth = "LoginToServerAuth";
            public readonly string LogOff = "LogOff";
            public readonly string FetchColumns = "FetchColumns";
            public readonly string LoginToServer = "LoginToServer";
            public readonly string RunSQL2 = "RunSQL2";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string Start = "Start";
            public const string LoginToServerAuth = "LoginToServerAuth";
            public const string LogOff = "LogOff";
            public const string FetchColumns = "FetchColumns";
            public const string LoginToServer = "LoginToServer";
            public const string RunSQL2 = "RunSQL2";
        }


        static readonly ActionParamsClass_FetchColumns s_params_FetchColumns = new ActionParamsClass_FetchColumns();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_FetchColumns FetchColumnsParams { get { return s_params_FetchColumns; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_FetchColumns
        {
            public readonly string database = "database";
            public readonly string table = "table";
        }
        static readonly ActionParamsClass_LoginToServer s_params_LoginToServer = new ActionParamsClass_LoginToServer();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_LoginToServer LoginToServerParams { get { return s_params_LoginToServer; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_LoginToServer
        {
            public readonly string serverName = "serverName";
            public readonly string userName = "userName";
            public readonly string password = "password";
        }
        static readonly ActionParamsClass_RunSQL2 s_params_RunSQL2 = new ActionParamsClass_RunSQL2();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_RunSQL2 RunSQL2Params { get { return s_params_RunSQL2; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_RunSQL2
        {
            public readonly string sql = "sql";
            public readonly string database = "database";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string About = "About";
                public readonly string Contact = "Contact";
                public readonly string Index = "Index";
                public readonly string Login = "Login";
            }
            public readonly string About = "~/Views/Home/About.cshtml";
            public readonly string Contact = "~/Views/Home/Contact.cshtml";
            public readonly string Index = "~/Views/Home/Index.cshtml";
            public readonly string Login = "~/Views/Home/Login.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_HomeController : WebSQL.Controllers.HomeController
    {
        public T4MVC_HomeController() : base(Dummy.Instance) { }

        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        partial void StartOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult Start()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Start);
            StartOverride(callInfo);
            return callInfo;
        }

        partial void LoginToServerAuthOverride(T4MVC_System_Web_Mvc_JsonResult callInfo);

        public override System.Web.Mvc.JsonResult LoginToServerAuth()
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.LoginToServerAuth);
            LoginToServerAuthOverride(callInfo);
            return callInfo;
        }

        partial void LogOffOverride(T4MVC_System_Web_Mvc_JsonResult callInfo);

        public override System.Web.Mvc.JsonResult LogOff()
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.LogOff);
            LogOffOverride(callInfo);
            return callInfo;
        }

        partial void FetchColumnsOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string database, string table);

        public override System.Web.Mvc.JsonResult FetchColumns(string database, string table)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.FetchColumns);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "database", database);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "table", table);
            FetchColumnsOverride(callInfo, database, table);
            return callInfo;
        }

        partial void LoginToServerOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string serverName, string userName, string password);

        public override System.Web.Mvc.JsonResult LoginToServer(string serverName, string userName, string password)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.LoginToServer);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "serverName", serverName);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "userName", userName);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "password", password);
            LoginToServerOverride(callInfo, serverName, userName, password);
            return callInfo;
        }

        partial void RunSQL2Override(T4MVC_System_Web_Mvc_JsonResult callInfo, string sql, string database);

        public override System.Web.Mvc.JsonResult RunSQL2(string sql, string database)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.RunSQL2);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "sql", sql);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "database", database);
            RunSQL2Override(callInfo, sql, database);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
